# Generated by Django 5.2.12 on 2026-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(db_column="FullName", max_length=200)),
                ("phone", models.CharField(db_column="Phone", max_length=50)),
                ("email", models.CharField(db_column="Email", max_length=200)),
                (
                    "appointment_preference",
                    models.CharField(
                        blank=True,
                        db_column="AppointmentPreference",
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True, db_column="Goal", default="", max_length=500
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, db_column="Message", default=""),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Beklemede", "Beklemede"),
                            ("Onaylandı", "Onaylandı"),
                            ("İptal", "İptal"),
                            ("Tamamlandı", "Tamamlandı"),
                        ],
                        db_column="Status",
                        default="Beklemede",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "AppointmentRequests",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="Title", max_length=300)),
                (
                    "content",
                    models.TextField(blank=True, db_column="Content", default=""),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, db_column="Excerpt", default="", max_length=500
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="ImageUrl", default="", max_length=500
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, db_column="Author", default="", max_length=200
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(auto_now_add=True, db_column="PublishedDate"),
                ),
                (
                    "is_published",
                    models.BooleanField(db_column="IsPublished", default=True),
                ),
                ("view_count", models.IntegerField(db_column="ViewCount", default=0)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "BlogPosts",
                "ordering": ["-published_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", default=""),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="ImageUrl", default="", max_length=500
                    ),
                ),
                ("order", models.IntegerField(db_column="Order", default=0)),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "GalleryImages",
                "ordering": ["order"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="Title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", default=""),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="ImageUrl", default="", max_length=500
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, db_column="ButtonText", default="", max_length=100
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, db_column="ButtonLink", default="", max_length=500
                    ),
                ),
                ("order", models.IntegerField(db_column="Order", default=0)),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "HeroSlides",
                "ordering": ["order"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NutritionProgram",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="Title", max_length=300)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", default=""),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="ImageUrl", default="", max_length=500
                    ),
                ),
                ("order", models.IntegerField(db_column="Order", default=0)),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "NutritionPrograms",
                "ordering": ["order"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(db_column="Title", max_length=300)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", default=""),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, db_column="Excerpt", default="", max_length=500
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="ImageUrl", default="", max_length=500
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(blank=True, db_column="Ingredients", default=""),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, db_column="Instructions", default=""),
                ),
                (
                    "prep_time",
                    models.IntegerField(blank=True, db_column="PrepTime", null=True),
                ),
                (
                    "cook_time",
                    models.IntegerField(blank=True, db_column="CookTime", null=True),
                ),
                (
                    "servings",
                    models.IntegerField(blank=True, db_column="Servings", null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, db_column="Difficulty", default="", max_length=50
                    ),
                ),
                ("order", models.IntegerField(db_column="Order", default=0)),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Recipes",
                "ordering": ["order"],
                "managed": False,
            },
        ),
    ]
